services:
  # --- СЕРВІС БОТА ---
  bot:
    build: .
    container_name: transport_bot_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./config/google_credentials.json:/app/config/google_credentials.json
      - ./assets:/app/assets
      - ./documents:/app/documents
    environment:
      - TZ=Europe/Kyiv

  # --- СЕРВІС БАЗИ ДАНИХ ---
  db:
    image: postgres:15-alpine
    container_name: transport_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Kyiv
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Зовнішній порт 5433 (на Мак) -> Внутрішній 5432 (у контейнері)
      - "5433:5432"

volumes:
  postgres_data: